# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "auth.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nauth.proto\x12\x0cmingdrlms.v2"(\n\x14\x41uthChallengeRequest\x12\x10\n\x08username\x18\x01 \x01(\t"&\n\x15\x41uthChallengeResponse\x12\r\n\x05nonce\x18\x01 \x01(\t"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t"\\\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x1f\n\x17\x61\x63\x63\x65ss_token_expires_in\x18\x03 \x01(\x03",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t"M\n\x14RefreshTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x1f\n\x17\x61\x63\x63\x65ss_token_expires_in\x18\x02 \x01(\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "auth_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUTHCHALLENGEREQUEST"]._serialized_start = 28
    _globals["_AUTHCHALLENGEREQUEST"]._serialized_end = 68
    _globals["_AUTHCHALLENGERESPONSE"]._serialized_start = 70
    _globals["_AUTHCHALLENGERESPONSE"]._serialized_end = 108
    _globals["_AUTHREQUEST"]._serialized_start = 110
    _globals["_AUTHREQUEST"]._serialized_end = 159
    _globals["_AUTHRESPONSE"]._serialized_start = 161
    _globals["_AUTHRESPONSE"]._serialized_end = 253
    _globals["_REFRESHTOKENREQUEST"]._serialized_start = 255
    _globals["_REFRESHTOKENREQUEST"]._serialized_end = 299
    _globals["_REFRESHTOKENRESPONSE"]._serialized_start = 301
    _globals["_REFRESHTOKENRESPONSE"]._serialized_end = 378
# @@protoc_insertion_point(module_scope)
