# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/v2/auth.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 3, "", "schema/v2/auth.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14schema/v2/auth.proto\x12\x0cmingdrlms.v2"(\n\x14\x41uthChallengeRequest\x12\x10\n\x08username\x18\x01 \x01(\t"&\n\x15\x41uthChallengeResponse\x12\r\n\x05nonce\x18\x01 \x01(\t"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t"\\\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x1f\n\x17\x61\x63\x63\x65ss_token_expires_in\x18\x03 \x01(\x03",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t"M\n\x14RefreshTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x1f\n\x17\x61\x63\x63\x65ss_token_expires_in\x18\x02 \x01(\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "schema.v2.auth_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUTHCHALLENGEREQUEST"]._serialized_start = 38
    _globals["_AUTHCHALLENGEREQUEST"]._serialized_end = 78
    _globals["_AUTHCHALLENGERESPONSE"]._serialized_start = 80
    _globals["_AUTHCHALLENGERESPONSE"]._serialized_end = 118
    _globals["_AUTHREQUEST"]._serialized_start = 120
    _globals["_AUTHREQUEST"]._serialized_end = 169
    _globals["_AUTHRESPONSE"]._serialized_start = 171
    _globals["_AUTHRESPONSE"]._serialized_end = 263
    _globals["_REFRESHTOKENREQUEST"]._serialized_start = 265
    _globals["_REFRESHTOKENREQUEST"]._serialized_end = 309
    _globals["_REFRESHTOKENRESPONSE"]._serialized_start = 311
    _globals["_REFRESHTOKENRESPONSE"]._serialized_end = 388
# @@protoc_insertion_point(module_scope)
