# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/v2/auth.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="schema/v2/auth.proto",
    package="mingdrlms.v2",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14schema/v2/auth.proto\x12\x0cmingdrlms.v2"(\n\x14\x41uthChallengeRequest\x12\x10\n\x08username\x18\x01 \x01(\t"&\n\x15\x41uthChallengeResponse\x12\r\n\x05nonce\x18\x01 \x01(\t"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t"\\\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x1f\n\x17\x61\x63\x63\x65ss_token_expires_in\x18\x03 \x01(\x03",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t"M\n\x14RefreshTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x1f\n\x17\x61\x63\x63\x65ss_token_expires_in\x18\x02 \x01(\x03\x62\x06proto3',
)


_AUTHCHALLENGEREQUEST = _descriptor.Descriptor(
    name="AuthChallengeRequest",
    full_name="mingdrlms.v2.AuthChallengeRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="username",
            full_name="mingdrlms.v2.AuthChallengeRequest.username",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=38,
    serialized_end=78,
)


_AUTHCHALLENGERESPONSE = _descriptor.Descriptor(
    name="AuthChallengeResponse",
    full_name="mingdrlms.v2.AuthChallengeResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="nonce",
            full_name="mingdrlms.v2.AuthChallengeResponse.nonce",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=80,
    serialized_end=118,
)


_AUTHREQUEST = _descriptor.Descriptor(
    name="AuthRequest",
    full_name="mingdrlms.v2.AuthRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="username",
            full_name="mingdrlms.v2.AuthRequest.username",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="response",
            full_name="mingdrlms.v2.AuthRequest.response",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=120,
    serialized_end=169,
)


_AUTHRESPONSE = _descriptor.Descriptor(
    name="AuthResponse",
    full_name="mingdrlms.v2.AuthResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="access_token",
            full_name="mingdrlms.v2.AuthResponse.access_token",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="refresh_token",
            full_name="mingdrlms.v2.AuthResponse.refresh_token",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="access_token_expires_in",
            full_name="mingdrlms.v2.AuthResponse.access_token_expires_in",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=171,
    serialized_end=263,
)


_REFRESHTOKENREQUEST = _descriptor.Descriptor(
    name="RefreshTokenRequest",
    full_name="mingdrlms.v2.RefreshTokenRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="refresh_token",
            full_name="mingdrlms.v2.RefreshTokenRequest.refresh_token",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=265,
    serialized_end=309,
)


_REFRESHTOKENRESPONSE = _descriptor.Descriptor(
    name="RefreshTokenResponse",
    full_name="mingdrlms.v2.RefreshTokenResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="access_token",
            full_name="mingdrlms.v2.RefreshTokenResponse.access_token",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="access_token_expires_in",
            full_name="mingdrlms.v2.RefreshTokenResponse.access_token_expires_in",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=311,
    serialized_end=388,
)

DESCRIPTOR.message_types_by_name["AuthChallengeRequest"] = _AUTHCHALLENGEREQUEST
DESCRIPTOR.message_types_by_name["AuthChallengeResponse"] = _AUTHCHALLENGERESPONSE
DESCRIPTOR.message_types_by_name["AuthRequest"] = _AUTHREQUEST
DESCRIPTOR.message_types_by_name["AuthResponse"] = _AUTHRESPONSE
DESCRIPTOR.message_types_by_name["RefreshTokenRequest"] = _REFRESHTOKENREQUEST
DESCRIPTOR.message_types_by_name["RefreshTokenResponse"] = _REFRESHTOKENRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthChallengeRequest = _reflection.GeneratedProtocolMessageType(
    "AuthChallengeRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _AUTHCHALLENGEREQUEST,
        "__module__": "schema.v2.auth_pb2",
        # @@protoc_insertion_point(class_scope:mingdrlms.v2.AuthChallengeRequest)
    },
)
_sym_db.RegisterMessage(AuthChallengeRequest)

AuthChallengeResponse = _reflection.GeneratedProtocolMessageType(
    "AuthChallengeResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _AUTHCHALLENGERESPONSE,
        "__module__": "schema.v2.auth_pb2",
        # @@protoc_insertion_point(class_scope:mingdrlms.v2.AuthChallengeResponse)
    },
)
_sym_db.RegisterMessage(AuthChallengeResponse)

AuthRequest = _reflection.GeneratedProtocolMessageType(
    "AuthRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _AUTHREQUEST,
        "__module__": "schema.v2.auth_pb2",
        # @@protoc_insertion_point(class_scope:mingdrlms.v2.AuthRequest)
    },
)
_sym_db.RegisterMessage(AuthRequest)

AuthResponse = _reflection.GeneratedProtocolMessageType(
    "AuthResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _AUTHRESPONSE,
        "__module__": "schema.v2.auth_pb2",
        # @@protoc_insertion_point(class_scope:mingdrlms.v2.AuthResponse)
    },
)
_sym_db.RegisterMessage(AuthResponse)

RefreshTokenRequest = _reflection.GeneratedProtocolMessageType(
    "RefreshTokenRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _REFRESHTOKENREQUEST,
        "__module__": "schema.v2.auth_pb2",
        # @@protoc_insertion_point(class_scope:mingdrlms.v2.RefreshTokenRequest)
    },
)
_sym_db.RegisterMessage(RefreshTokenRequest)

RefreshTokenResponse = _reflection.GeneratedProtocolMessageType(
    "RefreshTokenResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _REFRESHTOKENRESPONSE,
        "__module__": "schema.v2.auth_pb2",
        # @@protoc_insertion_point(class_scope:mingdrlms.v2.RefreshTokenResponse)
    },
)
_sym_db.RegisterMessage(RefreshTokenResponse)


# @@protoc_insertion_point(module_scope)
