syntax = "proto3";
package mingdrlms.v2;

// 端到端密钥生成请求
message E2EE_GenerateKeysRequest {
  string user_name = 1;
  bool force_regenerate = 2;
}

message E2EE_GenerateKeysResponse {
  int32 code = 1;
  string message = 2;
  uint32 registration_id = 3;
  uint32 pre_key_count = 4;
}

// 端到端预密钥包请求
message E2EE_PreKeyBundleRequest {
  string user_name = 1;
}

message E2EE_PreKeyBundleResponse {
  int32 code = 1;
  string message = 2;
  bytes identity_key = 3;
  uint32 registration_id = 4;
  uint32 device_id = 5;
  uint32 pre_key_id = 6;
  bytes pre_key_public = 7;
  uint32 signed_pre_key_id = 8;
  bytes signed_pre_key_public = 9;
  bytes signed_pre_key_signature = 10;
}
