if(NOT DEFINED PROTO_PY_BASE_DIR_FILE)
    message(FATAL_ERROR "PROTO_PY_BASE_DIR_FILE is not defined")
endif()
if(NOT EXISTS "${PROTO_PY_BASE_DIR_FILE}")
    message(FATAL_ERROR "Proto base directory file not found: ${PROTO_PY_BASE_DIR_FILE}")
endif()
if(NOT DEFINED PROTO_PY_FILENAME)
    message(FATAL_ERROR "PROTO_PY_FILENAME is not defined")
endif()
if(NOT DEFINED PROTO_PY_DEST_DIR)
    message(FATAL_ERROR "PROTO_PY_DEST_DIR is not defined")
endif()

set(_copied FALSE)
file(STRINGS "${PROTO_PY_BASE_DIR_FILE}" _base_dirs)
foreach(_base IN LISTS _base_dirs)
    message(STATUS "CopyGeneratedProtoPy checking ${_base} for ${PROTO_PY_FILENAME}")
    file(GLOB_RECURSE _matches "${_base}/${PROTO_PY_FILENAME}")
    message(STATUS "CopyGeneratedProtoPy matches: ${_matches}")
    foreach(_candidate IN LISTS _matches)
        if(EXISTS "${_candidate}")
            file(MAKE_DIRECTORY "${PROTO_PY_DEST_DIR}")
            file(COPY "${_candidate}" DESTINATION "${PROTO_PY_DEST_DIR}")
            set(_copied TRUE)
            break()
        endif()
    endforeach()
    if(_copied)
        break()
    endif()
endforeach()

if(NOT _copied)
    string(JOIN "; " _dirs_display ${_base_dirs})
    message(FATAL_ERROR "Failed to locate ${PROTO_PY_FILENAME} in any of: ${_dirs_display}")
endif()
