# Helper for pinning the protoc binary version used to generate *_pb2.py files
# and protobuf-c sources. This keeps CI, local dev, and release artifacts
# consistent regardless of the system protoc version provided by the OS.

set(DRLMS_PROTOC_VERSION_DEFAULT "28.3")
if(NOT DEFINED DRLMS_PROTOC_VERSION)
    set(DRLMS_PROTOC_VERSION "${DRLMS_PROTOC_VERSION_DEFAULT}" CACHE STRING
        "Pinned protoc version (major.minor[.patch]) used for schema generation" FORCE)
endif()

function(_drlms_parse_semver VERSION OUT_MAJOR OUT_MINOR OUT_PATCH)
    if(VERSION MATCHES "^([0-9]+)\\.([0-9]+)(\\.([0-9]+))?$")
        set(${OUT_MAJOR} "${CMAKE_MATCH_1}" PARENT_SCOPE)
        set(${OUT_MINOR} "${CMAKE_MATCH_2}" PARENT_SCOPE)
        if(CMAKE_MATCH_4)
            set(${OUT_PATCH} "${CMAKE_MATCH_4}" PARENT_SCOPE)
        else()
            set(${OUT_PATCH} "0" PARENT_SCOPE)
        endif()
    else()
        set(${OUT_MAJOR} "-1" PARENT_SCOPE)
        set(${OUT_MINOR} "-1" PARENT_SCOPE)
        set(${OUT_PATCH} "-1" PARENT_SCOPE)
    endif()
endfunction()

function(_drlms_format_semver MAJOR MINOR PATCH OUT_VAR)
    set(${OUT_VAR} "${MAJOR}.${MINOR}.${PATCH}" PARENT_SCOPE)
endfunction()

function(_drlms_versions_compatible CANDIDATE REQUIRED OUT_RESULT)
    _drlms_parse_semver("${CANDIDATE}" CAND_MAJOR CAND_MINOR CAND_PATCH)
    _drlms_parse_semver("${REQUIRED}" REQ_MAJOR REQ_MINOR REQ_PATCH)
    if(CAND_MAJOR LESS 0 OR REQ_MAJOR LESS 0)
        set(${OUT_RESULT} FALSE PARENT_SCOPE)
        return()
    endif()
    if(NOT CAND_MAJOR EQUAL REQ_MAJOR)
        set(${OUT_RESULT} FALSE PARENT_SCOPE)
        return()
    endif()
    if(NOT CAND_MINOR EQUAL REQ_MINOR)
        set(${OUT_RESULT} FALSE PARENT_SCOPE)
        return()
    endif()
    if(CAND_PATCH LESS REQ_PATCH)
        set(${OUT_RESULT} FALSE PARENT_SCOPE)
        return()
    endif()
    set(${OUT_RESULT} TRUE PARENT_SCOPE)
endfunction()

function(_drlms_detect_protoc_version PROTOC_BIN OUT_VERSION OUT_RAW)
    if(NOT EXISTS "${PROTOC_BIN}")
        set(${OUT_VERSION} "" PARENT_SCOPE)
        set(${OUT_RAW} "" PARENT_SCOPE)
        return()
    endif()
    execute_process(
        COMMAND "${PROTOC_BIN}" --version
        OUTPUT_VARIABLE RAW_VERSION
        ERROR_VARIABLE RAW_ERROR
        RESULT_VARIABLE PROC_RC
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT PROC_RC EQUAL 0)
        set(${OUT_VERSION} "" PARENT_SCOPE)
        set(${OUT_RAW} "${RAW_ERROR}" PARENT_SCOPE)
        return()
    endif()
    if(RAW_VERSION MATCHES "([0-9]+\\.[0-9]+(\\.[0-9]+)?)")
        set(${OUT_VERSION} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${OUT_VERSION} "" PARENT_SCOPE)
    endif()
    set(${OUT_RAW} "${RAW_VERSION}" PARENT_SCOPE)
endfunction()

function(_drlms_download_protoc VERSION OUT_BIN)
    if(NOT VERSION)
        message(FATAL_ERROR "_drlms_download_protoc called without version")
    endif()

    if(WIN32)
        set(ARCHIVE_NAME "protoc-${VERSION}-win64.zip")
        set(BIN_SUFFIX ".exe")
    elseif(APPLE)
        set(ARCHIVE_NAME "protoc-${VERSION}-osx-universal_binary.zip")
        set(BIN_SUFFIX "")
    else()
        set(ARCHIVE_NAME "protoc-${VERSION}-linux-x86_64.zip")
        set(BIN_SUFFIX "")
    endif()

    set(DOWNLOAD_BASE "${CMAKE_BINARY_DIR}/.drlms-protoc")
    file(MAKE_DIRECTORY "${DOWNLOAD_BASE}")
    set(ARCHIVE_PATH "${DOWNLOAD_BASE}/${ARCHIVE_NAME}")
    set(EXTRACT_DIR "${DOWNLOAD_BASE}/protoc-${VERSION}")
    set(EXPECTED_BIN "${EXTRACT_DIR}/bin/protoc${BIN_SUFFIX}")

    if(NOT EXISTS "${EXPECTED_BIN}")
        if(NOT EXISTS "${ARCHIVE_PATH}")
            set(DOWNLOAD_URL "https://github.com/protocolbuffers/protobuf/releases/download/v${VERSION}/${ARCHIVE_NAME}")
            message(STATUS "Downloading protoc v${VERSION} from ${DOWNLOAD_URL}")
            file(DOWNLOAD "${DOWNLOAD_URL}" "${ARCHIVE_PATH}" SHOW_PROGRESS STATUS DL_STATUS)
            list(GET DL_STATUS 0 DL_RC)
            if(NOT DL_RC EQUAL 0)
                list(GET DL_STATUS 1 DL_MSG)
                file(REMOVE "${ARCHIVE_PATH}")
                message(FATAL_ERROR "Failed to download protoc ${VERSION}: ${DL_MSG}")
            endif()
        endif()
        message(STATUS "Extracting protoc v${VERSION} to ${EXTRACT_DIR}")
        file(MAKE_DIRECTORY "${EXTRACT_DIR}")
        file(ARCHIVE_EXTRACT INPUT "${ARCHIVE_PATH}" DESTINATION "${EXTRACT_DIR}")
    endif()

    if(NOT EXISTS "${EXPECTED_BIN}")
        message(FATAL_ERROR "Downloaded protoc archive missing binary at ${EXPECTED_BIN}")
    endif()
    set(${OUT_BIN} "${EXPECTED_BIN}" PARENT_SCOPE)
endfunction()

function(drlms_require_protoc OUT_VAR)
    set(REQUIRED_VERSION "${DRLMS_PROTOC_VERSION}")
    if(NOT REQUIRED_VERSION)
        set(REQUIRED_VERSION "${DRLMS_PROTOC_VERSION_DEFAULT}")
    endif()

    set(CANDIDATES)
    if(DEFINED ENV{PROTOC})
        list(APPEND CANDIDATES "$ENV{PROTOC}")
    endif()
    if(PROTOC_EXECUTABLE)
        list(APPEND CANDIDATES "${PROTOC_EXECUTABLE}")
    endif()
    find_program(_PROTOC_IN_PATH protoc)
    if(_PROTOC_IN_PATH)
        list(APPEND CANDIDATES "${_PROTOC_IN_PATH}")
    endif()
    list(REMOVE_DUPLICATES CANDIDATES)

    foreach(CAND IN LISTS CANDIDATES)
        if(NOT CAND)
            continue()
        endif()
        _drlms_detect_protoc_version("${CAND}" DETECTED RAW)
        if(DETECTED)
            _drlms_versions_compatible("${DETECTED}" "${REQUIRED_VERSION}" COMPATIBLE)
            if(COMPATIBLE)
                message(STATUS "Using system protoc ${DETECTED} at ${CAND}")
                set(${OUT_VAR} "${CAND}" PARENT_SCOPE)
                set(PROTOC_EXECUTABLE "${CAND}" CACHE FILEPATH "Pinned protoc executable" FORCE)
                return()
            else()
                message(STATUS "Ignoring protoc ${DETECTED} at ${CAND}; requires v${REQUIRED_VERSION}")
            endif()
        endif()
    endforeach()

    _drlms_download_protoc("${REQUIRED_VERSION}" DOWNLOADED_BIN)
    _drlms_detect_protoc_version("${DOWNLOADED_BIN}" DL_VERSION RAW)
    if(NOT DL_VERSION)
        message(FATAL_ERROR "Failed to verify downloaded protoc v${REQUIRED_VERSION}")
    endif()
    message(STATUS "Using pinned protoc ${DL_VERSION} from ${DOWNLOADED_BIN}")
    set(${OUT_VAR} "${DOWNLOADED_BIN}" PARENT_SCOPE)
    set(PROTOC_EXECUTABLE "${DOWNLOADED_BIN}" CACHE FILEPATH "Pinned protoc executable" FORCE)
endfunction()
